In [1]:
import json
from pathlib import Path
from prompts.schemas import ContributionType, Area
import pandas as pd

## Load data

In [2]:
data_dir = Path('../data/extracted_data')
filename = 'entities_and_results.json'
with open(data_dir / filename) as f:
    data = json.load(f)

In [3]:
print(f'There are {len(data)} entries in the data.')

There are 49689 entries in the data.

### Make Dataframe for Entities

In [4]:
def standardize_usage(
    usage: list[str]
) -> str:
    for usage_entry in usage:
        if usage_entry not in ['Proposed Model', 'Baseline']:
            print(f'Found unexpected value {usage_entry}.')
            return usage_entry
    if 'Proposed Model' and 'Baseline' in usage:
        return 'Both'
    elif 'Proposed Model' in usage:
        return 'Proposed Model'
    elif 'Baseline' in usage:
        return 'Baseline'
    else:
        return ''

category_names = {
    'tasks': 'task',
    'datasets': 'dataset',
    'metrics': 'metric',
    'architectures': 'architecture',
    'methods': 'method',
    'pretrained_models': 'pretrained_model'
}


# Make dataframe for entities
entities_df_data = {
    'id': [],
    'category': [],
    'name': [],
    'quote': [],
    'usage': []
}

for id, entry in data.items():
    for category, extracted_entities in entry['entities'].items():
        for extracted_entity in extracted_entities:
            name = extracted_entity['name'].strip().lower()
            quote = extracted_entity['quote']
            if 'usage' in extracted_entity:
                usage = standardize_usage(extracted_entity['usage'])
            else:
                usage = ''
            entities_df_data['id'].append(id)
            entities_df_data['category'].append(category_names[category])
            entities_df_data['name'].append(name)
            entities_df_data['quote'].append(quote)
            entities_df_data['usage'].append(usage)

entities_df = pd.DataFrame(entities_df_data)

### Make dataframe for results

In [6]:
results_df_data = {
    'id': [],
    'dataset': [],
    'task': [],
    'metric': [],
    'result': []
}

for id, entry in data.items():
    for result in entry['results']:
        results_df_data['id'].append(id)
        results_df_data['dataset'].append(result['dataset'].strip().lower())
        results_df_data['task'].append(result['task'].strip().lower())
        results_df_data['metric'].append(result['metric'].strip().lower())
        results_df_data['result'].append(result['result'])

results_df = pd.DataFrame(results_df_data)

## Data Analysis

### Functions

### Entities

Get the total number of extracted entities.

In [7]:
print(len(entities_df))

437646

Get number of entries per category and number of unique values

In [8]:
entities_df.groupby('category').agg({'name': ['count', 'nunique']})

                    name
                   count nunique
category
architecture       72928   18673
dataset           103858   41788
method             84387   36794
metric             81641   11795
pretrained_model   24538    4579
task               70294   21094

Get the 20 most common entities per category.

In [9]:
# Get the 20 most common entities per category and their count
for category in entities_df['category'].unique():
    print(f'Category: {category}')
    print(entities_df.groupby('category').get_group(category)['name'].value_counts().head(20))
    print('\n')

Category: task
name
machine translation                2396
named entity recognition           1763
sentiment analysis                 1645
dependency parsing                  971
question answering                  939
neural machine translation          860
part-of-speech tagging              803
statistical machine translation     731
natural language inference          670
text classification                 652
word sense disambiguation           571
relation extraction                 537
coreference resolution              483
semantic role labeling              403
natural language generation         399
information extraction              382
sentiment classification            378
language modeling                   347
automatic speech recognition        339
semantic parsing                    333
Name: count, dtype: int64


Category: dataset
name
europarl                       924
conll-2003                     733
penn treebank                  667
wikipedia                      503
twitter                        396
squad                          372
imdb                           353
snli                           330
ontonotes                      283
mnli                           261
universal dependencies         254
glue                           251
gigaword                       237
sst-2                          231
yelp                           229
british national corpus        216
news commentary                191
simlex-999                     183
atis                           181
stanford sentiment treebank    177
Name: count, dtype: int64


Category: metric
name
accuracy                  8572
f1-score                  8568
bleu                      5462
precision                 3803
recall                    3474
f-score                   1861
f-measure                 1400
meteor                    1047
perplexity                 978
f1 score                   977
rouge                      864
bleu score                 746
ter                        729
rouge-l                    635
mean reciprocal rank       632
pearson correlation        557
word error rate            553
mean average precision     532
exact match                439
rouge-2                    425
Name: count, dtype: int64


Category: architecture
name
transformer                     4933
bert                            4499
lstm                            2625
roberta                         1394
bilstm                          1040
cnn                              735
bidirectional lstm               715
support vector machine           642
convolutional neural network     624
svm                              606
logistic regression              585
bi-lstm                          584
bart                             564
conditional random fields        548
gpt-2                            518
moses                            502
gru                              480
seq2seq                          476
t5                               427
rnn                              412
Name: count, dtype: int64


Category: method
name
logistic regression            863
expectation-maximization       797
multi-task learning            550
attention mechanism            538
tf-idf                         535
beam search                    494
data augmentation              445
reinforcement learning         403
support vector machine         393
back-translation               363
word2vec                       363
stochastic gradient descent    343
knowledge distillation         340
transfer learning              326
fine-tuning                    322
gibbs sampling                 304
giza++                         295
cosine similarity              270
support vector machines        262
distant supervision            261
Name: count, dtype: int64


Category: pretrained_model
name
bert                 3643
glove                2357
word2vec             1639
fasttext              952
roberta               809
elmo                  681
gpt-2                 374
mbert                 288
bert-base             261
xlm-r                 209
bart                  196
xlnet                 181
bert-base-uncased     178
multilingual bert     170
biobert               167
xlm-roberta           154
bert base             150
t5                    137
albert                135
distilbert            134
Name: count, dtype: int64

### Results

Get the number of extracted results.

In [10]:
print(len(results_df))
results_df.nunique()

86905

id         38209
dataset    28647
task       16055
metric      7928
result     11490
dtype: int64

## Combine entities from Entities and Results

In [11]:
results_as_entity_rows = []
for _, row in results_df.iterrows():
    dataset_row = {
        'id': row['id'],
        'category': 'dataset',
        'name': row['dataset'],
        'quote': '',
        'usage': ''
    }
    task_row = {
        'id': row['id'],
        'category': 'task',
        'name': row['task'],
        'quote': '',
        'usage': ''
    }
    metric_row = {
        'id': row['id'],
        'category': 'metric',
        'name': row['metric'],
        'quote': '',
        'usage': ''
    }
    results_as_entity_rows += [
        dataset_row,
        task_row,
        metric_row
    ]
entities_from_results_df = pd.DataFrame(results_as_entity_rows)

combined_df = pd.concat(
    [
        entities_df,
        entities_from_results_df
    ],
    ignore_index=True
)

Get the number of unique entities in the combined df

In [12]:
combined_df.groupby('category').agg({'name': ['count', 'nunique']})

                    name
                   count nunique
category
architecture       72928   18673
dataset           190763   46400
method             84387   36794
metric            168546   12844
pretrained_model   24538    4579
task              157199   22292

## Check for duplicates